### ISSUE TITLE
中間振り返り

### ISSUE THREAD

**Issue by takat0627** [takat0627/rails-tutorial#12]
# 進捗
- 想像よりスラスラいかずSection8まで終わったところです．
- 特に詰まったと思った点はSection8のセッションに関する点でその理解確認をしたいと思っています．
- それ以外は詰まってはいないものの，しっかり理解しながらコードを書いて実際に動いているところを確認，見比べるかつ学んだことを少しずつまとめてとしていたせいか1週間の限られた時間の中では半分くらいが限界でした．．．
- （Rails風な）Rubyの文法について <#7> 
  - Rubyの文法を根本的に理解していなかったのでこの章はじっくり読み手元でもいろいろ試しながらやったため少し時間がかかりました
  - 感じたこと
    - 柔軟性の高さに驚きばかりでした．
      - 特に省略できる箇所が多すぎるが故に初見殺しだなとも思いました
      - 暗黙な戻り値という概念がさらに初見殺しだなと思いました．
    - 以前少しだけ触ったことがあったのですが，本当に少しだったため完全にPythonライクという印象しか残ってませんでした
      - インデントも「言語として」重要だと完全に思い込んでいました

# セッションの理解確認
## Railsにおける一時的なセッション<#11>
まだ一時的なセッションまでしかやっていないので現状のセッションに関する理解確認
- セッション情報の流れ
  1. サーバーはセッション情報を暗号化しレスポンスのset-cookie属性にセットして送る（この値は毎回異なる）
  2. ブラウザはサーバから受け取った暗号化されたセッション情報を受け取って保存する（値が変わるので毎回保存する）
  3. ブラウザは保存されたクッキー情報をリクエストヘッダーのCookieへ含めてサーバへ送信
  4. サーバーは受け取ったクッキー情報を復号してセッション情報を扱う
- 上記の流れの中でログインがされたらユーザIDがセッション情報に含まれて一緒に送信される

# 質問1
### コミットをまとめるタイミング
1. コミットはある程度まとめてからプルリクを送る
2. プルリクがapproveされたタイミングでまとめる

### コミットとプルリクの粒度
- どの大きさでコミットをまとめるのか（するのか）
  - hogehogeコントローラーを追加した
  - hogehogeコントローラーに関するテストを追加した
  - etc...
- どの大きさでプルリクを送るのか
  - 特定の目的（機能追加などに加えてファイルの言い回し変更など）のために変更を加えたならプルリクを送る

# 質問2
## ブランチの運用方法
<details open>
<summary>ブランチの切り方について</summary>

- `A successful Git branching model`を参考にしました
- 序盤の切り方
  - ローカルでdevelopブランチを切って，その先でFeatureブランチを切る
  - Featureブランチが終わったらローカルのdevelopブランチ（最新をfetch後）へself merge
  - ローカルのdevelopブランチをorigin/developへpush
  - origin/developブランチからorigin/mainブランチへself merge
  - origin/mainブランチをfetchしてローカルmainへマージ（ここ個人開発なのでfast-forwardでしかありませんでした）
- 途中で気づいた違和感
  - コミットが大量にmainへ反映されてしまう
    - rebaseでコミットをまとめることを知らなかった
    - プルリク後のマージでsquash&mergeを選択できることを知らなかった
    - 途中からmainへのマージはコミットをまとめてマージ（#質問1）
  - そもそもリモートブランチとしてあげるのはどのブランチなのか（#質問2）
    - mainブラントとdevelopブラントのみをリモートで追跡させて，それ以外はすべてローカルで管理していた
    - 結局それではプルリク送る時点ではdevelopからmainへのプルリクであり，どんなFeatureブランチからの情報なのかが消えてしまっている
    - ひとまずdevelop/Feature名（トピック名）としてローカルでブランチを切って，それをそのままリモートで追跡，プルリク発行に使用
- 今現在の切り方
  - 最新のローカルmainブランチからdevelop/Feature名（branch-a）を切る（結果として最新のdevelopブランチからFeatureブランチを切っているのと同じような振る舞いを模倣）
  - 以降 branch-aで作業し，リモートでもorigin/branch-aを追跡させる
  - ひと通り作業が終わったらorigin/branch-aからorigin/mainへプルリクを発行しself merge（コミットはここでまとめる）
  - 最後にorigin/mainをfetchしてmainブランチを最新に（本来はここでdevelopブランチはmainの結果を取り込む）
</details>

### developブランチはどう運用するのか
- レビューなしの個人開発なのでコンフリクトなどは起きませんでしたが，序盤のような切り方が一般的か
- トピックブランチはローカルでのみで完結させてプルリクではdevelopからマージするのか
  - もしくは今やってるようなdevelopブランチから切ったトピックブランチからmainへプルリクを送ってもいいのか（そうすると完全にdevelopブランチのある意味が薄れそうな予感）
  - 本番の環境だとmainはリリース用のブランチで，レビューなどはdevelopブランチに対して行うのがやはり一般的なのか

**Comment by nyamadori** [comment]
日本人だけの開発チームであれば、コミットメッセージは日本語でいいと思いました。

**Comment by takat0627** [comment]
@nyamadori 
今回のコミットは一旦英語で統一して，二週目は日本語でコミットしていこうと思います！
振り返りでのたくさんのコメントありがとうございました🙇‍♂️
次回もよろしくお願いします．
